/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/model.glb 
Author: Huuxloc (https://sketchfab.com/rjh41)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/original-backrooms-e5c6b30995ff442d9852a1dd697aaef1
Title: Original Backrooms
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.25}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.5, 1.416, -2.739]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.Object_8.geometry} material={materials.PlugSocket} />
            <mesh geometry={nodes.Object_9.geometry} material={materials.GreenSkirting} />
            <mesh geometry={nodes.Object_10.geometry} material={materials.BR_2} />
            <mesh geometry={nodes.Object_11.geometry} material={materials.StripeWallpaper} />
            <mesh geometry={nodes.Object_12.geometry} material={materials.Dot_Wallpaper} />
          </group>
          <group position={[-3.842, 2.143, 1.4]}>
            <mesh geometry={nodes.Object_16.geometry} material={materials.Ceiling_Grid} />
            <mesh geometry={nodes.Object_17.geometry} material={materials.Ceiling_Lights} />
          </group>
          <mesh geometry={nodes.Object_4.geometry} material={materials.Vent} position={[-2.246, 2.15, -1.332]} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.Piece1} position={[-5.461, 1.416, 5.699]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.NewCarpet} position={[0.016, 0.006, -5.539]} />
          <mesh geometry={nodes.Object_19.geometry} material={materials.CeilingTile} position={[-3.842, 2.143, 1.4]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model.glb')
